import { Property } from "@/types/property";

export const sampleProperties: Property[] = [
  {
    id: "land-001",
    type: "land",
    title: "새만금 산업용지 투자 토지",
    description: "새만금 산업·연구용지 내 투자용 토지. 새만금 내부도로 접면, 군산IC 15분거리. 산업단지 개발 확정 구역으로 향후 높은 투자 수익이 기대됩니다.",
    price: 450000000,
    priceUnit: "total",
    address: "전북특별자치도 군산시 새만금로",
    area: 500,
    zoning: "새만금 산업·연구용지",
    landUse: "잡종지",
    floorAreaRatio: 200,
    buildingCoverageRatio: 60,
    images: [],
    features: ["새만금", "산업용지", "투자적합", "IC인접"],
    status: "available",
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
  },
  {
    id: "land-002",
    type: "land",
    title: "군산 옥도면 관광레저용지",
    description: "새만금 관광레저용지 내 위치. 새만금 방조제 인접으로 해양관광 개발에 최적입니다. 새만금 국제공항 예정지와 가깝습니다.",
    price: 680000000,
    priceUnit: "total",
    address: "전북특별자치도 군산시 옥도면",
    area: 800,
    zoning: "새만금 관광레저용지",
    landUse: "전",
    images: [],
    features: ["관광레저", "해양관광", "공항인접", "대형필지"],
    status: "available",
    createdAt: "2024-02-01",
    updatedAt: "2024-02-01",
  },
  {
    id: "land-003",
    type: "land",
    title: "김제 광활면 농생명용지",
    description: "새만금 농생명용지 내 토지. 스마트팜·농식품 가공시설 건축 가능. 만경강 인접, 용수 공급 우수. 농생명 클러스터 조성 예정지.",
    price: 320000000,
    priceUnit: "total",
    address: "전북특별자치도 김제시 광활면",
    area: 600,
    zoning: "새만금 농생명용지",
    landUse: "답",
    floorAreaRatio: 100,
    buildingCoverageRatio: 40,
    images: [],
    features: ["농생명", "스마트팜", "용수우수", "클러스터"],
    status: "available",
    createdAt: "2024-02-10",
    updatedAt: "2024-02-10",
  },
  {
    id: "factory-001",
    type: "factory",
    title: "군산 국가산업단지 제조공장",
    description: "군산 국가산업단지 내 제조업 공장 매매. 3상 전력 300kW 인입, 천장고 10m. 화물 하역장 완비. 군산항 20분, 군산IC 10분 거리.",
    price: 2200000000,
    priceUnit: "total",
    address: "전북특별자치도 군산시 오식도동 군산국가산단",
    area: 500,
    buildingArea: 420,
    zoning: "일반공업지역",
    images: [],
    features: ["국가산단", "천장고10m", "하역장완비", "항만인접"],
    status: "available",
    factoryType: "일반공장",
    ceilingHeight: 10,
    electricity: "3상 300kW",
    waterSupply: true,
    gasSupply: true,
    loadingDock: true,
    yearBuilt: 2016,
    createdAt: "2024-01-20",
    updatedAt: "2024-01-20",
  },
  {
    id: "factory-002",
    type: "factory",
    title: "군산 2산단 자동차부품 공장",
    description: "군산 제2산업단지 내 자동차부품 제조 공장. 대형 프레스 설비 가동 가능. 전용 크레인 설치 완료. 군장산단 인접으로 물류 최적.",
    price: 3800000000,
    priceUnit: "total",
    address: "전북특별자치도 군산시 소룡동 군산2산단",
    area: 700,
    buildingArea: 620,
    zoning: "일반공업지역",
    images: [],
    features: ["자동차부품", "크레인설치", "대형설비", "물류최적"],
    status: "available",
    factoryType: "일반공장",
    ceilingHeight: 12,
    electricity: "3상 500kW",
    waterSupply: true,
    gasSupply: true,
    loadingDock: true,
    yearBuilt: 2012,
    createdAt: "2024-02-05",
    updatedAt: "2024-02-05",
  },
  {
    id: "factory-003",
    type: "factory",
    title: "새만금 식품가공 공장 신축부지",
    description: "새만금 농생명 클러스터 인접 식품가공 공장 부지. HACCP 인증 설계 가능. 급배수 인프라 완비 예정. 새만금 내부도로 직접 연결.",
    price: 12000000,
    priceUnit: "per-pyeong",
    address: "전북특별자치도 군산시 새만금로",
    area: 550,
    buildingArea: 0,
    zoning: "새만금 산업·연구용지",
    images: [],
    features: ["식품가공", "신축가능", "HACCP", "인프라완비"],
    status: "available",
    factoryType: "식품공장",
    ceilingHeight: 0,
    electricity: "인입가능",
    waterSupply: true,
    gasSupply: true,
    loadingDock: false,
    yearBuilt: 0,
    createdAt: "2024-02-15",
    updatedAt: "2024-02-15",
  },
];
